ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
import home
from home import views
#from product import views as ProductView
from order import views as OrderView
from user import views as UserView
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    path('selectLanguage', views.selectLanguage, name='selectLanguage'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('savelangcur', views.savelangcur, name='savelangcur'),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('currencies/', include('currencies.urls')),
    path('jet', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    
    path(_('aboutus/'), views.aboutus, name='aboutus'),
    path(_('contactus/'), views.contactus, name='contactus'),
    path('policies&terms/', views.policies8terms, name='policies&terms'),
    path('customerservice/', views.customerservice, name='customerservice'),
    path('sales/', views.sales, name='sales'),
    path('giftcards/', views.giftcards, name='giftcards'),

    #path('checkout/', views.checkout, name='checkout'),

    path('product/', include('product.urls')),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),

    path(_('admin/'), admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('shopcart/', OrderView.shopcart, name='shopcart'),
    path('login/', UserView.login_form, name='login_form'),
    path('logout/', UserView.logout_form, name='logout_form'),
    path('logout/', include('user.urls')),
    path('signup/', UserView.signup_form, name='signup_form'),
    path('faq/', views.faq, name='faq'),
    #path('ajaxtest/', views.ajaxtest, name='ajaxtest'),
    #path('ajaxpost/', views.ajaxpost, name='ajaxpost'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    prefix_default_language = False

    #path('user_panel/', UserView.user_panel_form, name='user_panel_form'),
 ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""if settings.DEBAG: #new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)"""
    

home/urls.py
from django.conf.urls import handler400, handler404
from django.urls import path, include
from . import views
from user import views as UserView

urlpatterns = [
    path('', views.index, name='index'),
    #path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
]


#handler404 = 'index.views.error_404_view'

order/urls.py
from collections import namedtuple
from django.urls import path, include
from . import views
from user import views as UserView

urlpatterns = [
    path('', views.index, name='index'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('upgshopcart/<int:id>', views.upgshopcart, name='upgshopcart'),
    path('dcrshopcart/<int:id>', views.dcrshopcart, name='dcrshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct', views.orderproduct, name='orderproduct'),
    path('orderconfiramation/<int:id>', views.orderconfiramation, name='orderconfiramation'),
]

order/models.py
from django.db.models import fields

from django.forms import ModelForm
from product.models import Product
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
from product.models import Product, Variants






# Create your models here.
class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True)
    purchased_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.product.title
    
    
    @property
    def price(self):
        return (self.product.price)
    

    @property
    def amount(self):
        return (self.quantity * self.product.price)
    

    @property
    def varamount(self):
        return (self.quantity * self.variant.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']



class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(blank=True, max_length=300)
    address = models.CharField(blank=True, max_length=300)
    city = models.CharField(blank=True, max_length=300)
    country = models.CharField(blank=True, max_length=300)
    total = models.FloatField()
    status = models.CharField(choices=STATUS, max_length=10, default='New')
    ip = models.CharField(blank=True, max_length=50)
    adminnote = models.CharField(blank=True, max_length=200)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name



class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'address', 'city', 'country']



class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

    

order/views.py
#from product.models import Categorie
#import product
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from order.models import Order, OrderForm, OrderProduct, ShopCartForm, ShopCart
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string
#from django.contrib.auth.models import User
from product.models import Categorie, Product, Images, Variants
from home.models import Setting
from product.models import Categorie
from user.models import UserProfile





# Create your views here.

def index(request):
    return HttpResponse("Order Page")


@login_required(login_url='/login') # Check Login
def addtoshopcart(request, id):
    url = request.META.get('HTTP_REFERER') #get last url
    current_user = request.user # Access User Session information
    product= Product.objects.get(pk=id)
    variantid = request.POST.get('variantid')  # from variant add to cart


    chechproduct = ShopCart.objects.filter(product_id=id) # Check product in shopcart
    if chechproduct:
        control = 1 # The product is in the cart
    else:
        control = 0 # The product is not in the cart

    if product.variant != 'None':
        
        checkinvariant = ShopCart.objects.filter(variant_id=variantid, user_id=current_user.id)  # Check product in shopcart
        if checkinvariant:
            control = 1 # The product is in the cart
        else:
            control = 0 # The product is not in the cart"""
    else:
        checkinproduct = ShopCart.objects.filter(product_id=id, user_id=current_user.id) # Check product in shopcart
        if checkinproduct:
            control = 1 # The product is in the cart
        else:
            control = 0 # The product is not in the cart"""
    
    if request.method == 'POST': # if there is a post
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control==1: # Update shopcart
                if product.variant == 'None':
                    data = ShopCart.objects.get(product_id=id, user_id=current_user.id)
                else:
                    data = ShopCart.objects.get(product_id=id, variant_id=variantid, user_id=current_user.id)

                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save() # Save data
            else: # Insert to Shopcart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.variant_id = variantid
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, "Product added to Shopcart.")
        return HttpResponseRedirect(url)

    else: # if there is no post
        if control == 1: # Update shopcart
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()
        else: # Update to Shopcart
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.variant_id =None
            data.save()
        messages.success(request, 'Product added to Shopcart.')
        return HttpResponseRedirect(url)

    #return  HttpResponse(str(id))


def shopcart(request):
    category = Categorie.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    shoppingcart = ShopCart.objects.filter(user_id=current_user.id)
    setting = Setting.objects.get(pk=1)
    total = 0
    qnt = 0 # single product quantity.
    total_products = 0

    for rs in shopcart:
        total += rs.price * rs.quantity
    
    for rs in shoppingcart:
        total_products += rs.quantity

    context = { 'shopcart': shopcart,
                'shoppingcart': shoppingcart,
                'category': category,
                'setting': setting,
                'total' : total,
                'total_products': total_products
                }
    return render(request, 'shopcart_products.html', context)


@login_required(login_url='/login') # Check Login
def deletefromcart(request, id):
    url = request.META.get('HTTP_REFERER') #get last url
    current_user = request.user


    ShopCart.objects.filter(id=id).delete()
    messages.success(request, 'You have deleted the item from the Shopcart!')

    return HttpResponseRedirect(url)



def upgshopcart(request, id):
    last_url = request.META.get('HTTP_REFERER')
    data = ShopCart.objects.get(product_id=id)
    product = Product.objects.get(id=id)

    if data.quantity == product.amount:
        messages.info(request, "Can't add more products than whats already in stock!")
    else:
        data.quantity += 1
    
    data.save()

    return HttpResponseRedirect(last_url)


def dcrshopcart(request, id):
    last_url = request.META.get('HTTP_REFERER')
    data = ShopCart.objects.get(product_id=id)
    #product = Product.objects.get(product_id=id)
    
    if data.quantity < 1:
        messages.info(request, 'Your product quantity value is already 0!')
    else:
        data.quantity -= 1
    
    data.save()

    return HttpResponseRedirect(last_url)



def orderproduct(request):
    category = Categorie.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    shoppingcart = ShopCart.objects.filter(user_id=current_user.id)
    profile = UserProfile.objects.get(user_id=current_user.id)
    setting = Setting.objects.get(pk=1)
    total = 0
    total_products = 0

    for rs in shopcart:
        total += rs.price * rs.quantity
    
    for rs in shoppingcart:
        total_products += rs.quantity    
    
    url = request.META.get('HTTP_REFERER') #get last url
    if total_products < 1:
        messages.success(request, "Your cart is empty. Can't proceed with payment!")
        return HttpResponseRedirect(url)
    else:

        if request.method == 'POST': #If there is a post
            form = OrderForm(request.POST)
            if form.is_valid():
                # Send Credit card to bank, If the bank responds ok, continue, if not, hsow the error.

                data = Order()
                data.first_name = form.cleaned_data['first_name'] # get product quantity from form
                data.last_name = form.cleaned_data['last_name']
                data.address = form.cleaned_data['address']
                data.city = form.cleaned_data['city']
                data.country = form.cleaned_data['country']
                data.phone = form.cleaned_data['phone']
                data.user_id = current_user.id
                data.total = total
                data.ip = request.META.get('REMOTE_ADDR')
                ordercode = get_random_string(5).upper() # Random code
                data.code = ordercode
                data.save()

                # Move Shopping cart items to Order Products items

                for rs in shoppingcart:
                    detail = OrderProduct()
                    detail.order_id     = data.id # Order Id
                    detail.product_id   = rs.product_id
                    detail.user_id      = current_user.id
                    detail.quantity     = rs.quantity
                    
                    if rs.product.variant == 'None':
                        detail.price    = rs.product.price
                    else:
                        detail.price = rs.variant.price
                        
                    detail.variant_id   = rs.variant_id
                    detail.amount        = rs.amount
                    detail.save()

                    # ***Reduce quantity of sold product from Amount of Product

                    if  rs.product.variant=='None':
                        product = Product.objects.get(id=rs.product_id)
                        product.amount -= rs.quantity
                        product.save()
                    else:
                        product = Product.objects.get(id=rs.product_id)
                        variant = Variants.objects.get(id=rs.variant_id)
                        variant.quantity -= rs.quantity
                        product.amount -= rs.quantity
                        variant.save()
                        product.save() 

                ShopCart.objects.filter(user_id=current_user.id).delete() # Clear & delete shopcart
                request.session['cart_items'] = 0
                messages.success(request, 'Your Order has been completed. Thank you for your interest.')
                return HttpResponseRedirect("/order/orderconfiramation/" + str(detail.order_id))
                
                    
            else:
                messages.warning(request, form.errors)
                return HttpResponseRedirect("/order/orderproduct")
            
        

        form = OrderForm()

        context = { 'shopcart': shopcart,
                    'shoppingcart': shoppingcart,
                    'category': category,
                    'setting': setting,
                    'total' : total,
                    'total_products': total_products,
                    'profile': profile,
                    }
        return render(request, 'Order_Form.html', context)


def orderconfiramation(request, id):
    current_user = request.user
    category = Categorie.objects.all()
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    data = Order.objects.get(id=id, user=current_user.id)
    ordercode = data.code
    total = 0
    total_products = 0

    for rs in shopcart:
        total += rs.price * rs.quantity
    
    for rs in shopcart:
        total_products += rs.quantity

    return render(request, 'Order_Completed.html',{'ordercode': ordercode, 'category': category,
                                                    'total':total, 'total_products': total_products,  })

order/templates/Order_Form.html
{% extends 'homebase.html' %}
{% load currency %}

{% block title %} Order Page {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Page</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div  class="row">
                <Form action="" method="post">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <div class="billing-details">

                            <div class="section-title">
                                <h4 class="title">Shipping Details</h4>
                            </div>
                            <p><label for="id_first_name">First name:</label>
                                <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name"></p>
                            <p><label for="id_last_name">Last name:</label>
                                <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
                            <p><label for="id_address">Address:</label>
                                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
                            <p><label for="id_phone">Phone:</label>
                                <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="20" id="id_phone"></p>
                            <p><label for="id_city">City:</label>
                                <select name="city" class="input" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="İstanbul">Istanbul</option>
                                    <option value="Ankara">Ankara</option>
                                    <option value="İzmir">Izmir</option>
                                    <option value="Bursa">Bursa</option>
                                    <option value="Konya">Konya</option>
                                    <option value="Yozgat">Yozgat</option>
                                </select></p>
                            <p><label for="id_first_name">Country :</label>
                                <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}"></p>
                            <div class="pull-right">
                                <button type="submit" class="primary-btn">Complete Order</button>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="shiping-methods">
                            <div class="section-title">
                                <h4 class="title">Shiping Methods</h4>
                            </div>
                            <div class="input-checkbox">
                                <input type="radio" name="shipping" id="shipping-1" checked>
                                <label for="shipping-1">Free Shiping -  $0.00</label>
                                <div class="caption">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                        <p>
                                </div>
                            </div>
                            <div class="input-checkbox">
                                <input type="radio" name="shipping" id="shipping-2">
                                <label for="shipping-2">Standard - $4.00</label>
                                <div class="caption">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                        <p>
                                </div>
                            </div>
                        </div>
                    </div>

                </Form>

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Shopcart Product List Review</h3>
                        </div>
                                                <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Product</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Quantity</th>
                                <th class="text-center">Total</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for rs in shopcart %}
                                <tr>
                                    <td class="thumb">
                                        {% if rs.variant.image_id  > 0 %}
                                            <img src="{{rs.variant.image }}" alt="">
                                        {% else %}
                                            <img src="{{rs.product.image.url}}" alt="">
                                        {% endif %}
                                    </td>
                                    <td class="details">
                                        <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{rs.product}} {{ rs.variant.size }} {{ rs.variant.color }}</a>  </td>
                                    <td class="price text-center"><strong>
                                        {% if rs.product.variant == 'None' %}
                                            {{ rs.product.price|currency:request.session.currency }} {{ request.session.currency }}
                                        {% else %}
                                            {{ rs.variant.price|currency:request.session.currency }} {{ request.session.currency }}
                                        {% endif %}
                                    </strong><br></td>
                                    
                                    <td class="qty text-center"><strong>
                                        {{ rs.quantity }}
                                    </strong></td>
                                    <td class="total text-center"><strong class="primary-color">
                                        {% if rs.product.variant == 'None' %}
                                            {{ rs.amount|currency:request.session.currency }} {{ request.session.currency }}
                                        {% else %}
                                            {{ rs.varamount|currency:request.session.currency }} {{ request.session.currency }}
                                        {% endif %}
                                        
                                    </strong>
                                </tr>

                            {% endfor %}

                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SUBTOTAL</th>
                                <th colspan="2" class="sub-total">{{ total|currency:request.session.currency }} {{ request.session.currency }}</th>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SHIPING</th>
                                <td colspan="2">Free Shipping</td>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>TOTAL</th>
                                <th colspan="2" class="total">{{ total|currency:request.session.currency }} {{ request.session.currency }}</th>
                            </tr>
                            </tfoot>
                        </table>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

order/templates/Order_completed.html
{% extends 'homebase.html' %}

{% block title %} Order Complated {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Complated</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Complated</h3>
                        </div>
                        <hr>
                        <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                        <hr>
                        <h3>Your order is completed</h3>
                        <h3>Order Code : {{ ordercode }}</h3>
                        <h3>Thank You</h3>
                        <hr>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}